### ISSUE TITLE
Управление

### ISSUE THREAD

**Issue by dimamelnik22** [dimamelnik22/temporary-name-for-study-practice#4]
Реализовать управление мышью, учитывая поиск оптимального пути, достижимости цели (возможно за несколько ходов) и пересечение с другими объектами.

- [x] Управление по нажатию мышью на клетку
- [ ] Атака по нажатию мышью на врага
- [ ] Оптимальный обход лавы
- [ ] Удобная смена хода

**Comment by zarond** [comment]
Добавляю, но работает хуже чем хотелось бы, что то не так с системой координат. Дима Теппоев, у тебя как координаты устроены?
