### ISSUE TITLE
Механика сражений

### ISSUE THREAD

**Issue by dimamelnik22** [dimamelnik22/temporary-name-for-study-practice#7]
Реализовать концепт механики сражений на практике

- [x] Описать пример поведения NPC
- [x] Передвижение NPC по полю
- [ ] Обнаружение и обход лавы для NPC
- [x] Поочередный ход всех NPC
- [x] Учет оставшихся очков здоровья NPC
- [x] Взаимодействие с персонажем
- [ ] Балансировка очков передвижения и выбора действий по поведению

**Comment by dimamelnik22** [comment]
Готов класс, предоставляющий набор действий для NPC на текущий ход.
Описание:
-получаем атаку, защиту и передвижение через соответствующие методы Get
-обновляем набор действий через NextStep()
-обновляем запас хода через SetSubsteps()

**Comment by Spiryacova** [comment]
NPC забирают параметры из набора действий, случайно передвигаются пока рядом нет игрока/других NPC, иначе пытаются их атаковать. Преследуют цель по прямой, игнорируя препятствия.
